let allMusic = [
		"ABBA - The Winner Takes It All.mp3",
		"Cannibal - Tally Hall (16-bit chiptune cover).mp3",
		"Christell - Dubidubidu.mp3",
		"Connor Crow - Fallen Down but its ragtime.mp3",
		"DEAF KEV - Invincible.mp3",
		"DaymanOurSavior - Snow halation but shawty's like a melody in my head.mp3",
		"Earth, Wind & Fire - Can't Let Go.mp3",
		"Earth, Wind & Fire - In the Stone.mp3",
		"Electric Light Orchestra - Showdown (Official Audio)-(p).mp3",
		"Evanescence - Bring Me To Life.mp3",
		"Finger Eleven - Paralyzer.mp3",
		"Flight Facilities - Crave You feat. Giselle.mp3",
		"GIGI D'AGOSTINO - L'AMOUR TOUJOURS.mp3",
		"Guru Josh Project - Infinity.mp3",
		"Home - We're Finally Landing.mp3",
		"Ian Taylor - Baroque.mp3",
		"Ian Taylor - Yesteryear.mp3",
		"Let The Bodies Hit The Floor.mp3",
		"MC MENTAL - MC MENTAL at his best.mp3",
		"Mary J. Blige - Family Affair.mp3",
		"Michael Gray - The Weekend.mp3",
		"Mio mao ~ sped up.mp3",
		"Old RuneScape Soundtrack - Harmony.mp3",
		"Purple Engineer - In The Virtual End F---ing extreme low quality.mp3",
		"Scattle - Knock Knock.mp3",
		"Seatbelts - Cats on Mars.mp3",
		"Sooty Shearwater - Lonely Rolling Photograph.mp3",
		"Steven Universe - Soundtrack- Opening - (Instrumental) Official-(p).mp3",
		"The Buggles - Video Killed The Radio Star.mp3",
		"The Spiral Den - His Theme But I Lost My Hopes And Dreams.mp3",
		"TheFatRat - Time Lapse.mp3",
		"TheFatRat - Unity.mp3",
		"TheFatRat - Xenogenesis.mp3",
		"To the Gateway - Super Mario Galaxy Music.mp3",
		"Trance - 009 Sound System Dreamscape.mp3",
		"Underbase - Fallen Down.mp3",
		"Valve - Portal Radio.mp3",
		"pet in tv OST - M2.mp3",
];
