let allMusic = [
		"bodies.mp3",
		"bring_me_to_life.mp3",
		"cannibal_16bit.mp3",
		"cant_let_go.mp3",
		"cats_on_mars.mp3",
		"family_affair.mp3",
		"in_the_stone.mp3",
		"infinity.mp3",
		"invincible.mp3",
		"knock_knock.mp3",
		"lamour_toujours.mp3",
		"lonely_rolling_star.mp3",
		"m2.mp3",
		"mc_mental_at_his_best.mp3",
		"mio_mao_sped_up.mp3",
		"paralyzer.mp3",
		"portal_radio.mp3",
		"showdown.mp3",
		"sound_system_dreamscape.mp3",
		"the_weekend.mp3",
		"the_winner_takes_it_all.mp3",
		"time_lapse.mp3",
		"to_the_gateway.mp3",
		"unity.mp3",
		"were_finally_landing.mp3",
		"xenogenesis.mp3",
];

let allArtist = [
		"Drowning Pool",
		"Evanescence",
		"Tally Hall",
		"Earth, Wind & Fire",
		"Yoko Kanno",
		"Mary J. Blige",
		"Earth, Wind & Fire",
		"Guru Josh Project",
		"DEAF KEV",
		"Scattle",
		"Gigi D'Agostino",
		"Saki Kabata",
		"Suguru Yamaguchi (Pet in TV)",
		"MC MENTAL",
		"Piero Barbetti",
		"Finger Eleven",
		"Kelly Bailey",
		"Electric Light Orchestra",
		"Trance",
		"Michael Gray",
		"ABBA",
		"TheFatRat",
		"Mahito Yokota",
		"TheFatRat",
		"Home",
		"TheFatRat",
]
